### ISSUE TITLE
Cannot open the file

### ISSUE THREAD

**Issue by scottw-finao** [oicr-gsi/rawprintserver#2]
When installed as a service on windows 7, whenever you try to start the service it errors out saying it 'cannot open the file' - I'm assuming 'the file' is the exe. We have tried moving it into the system path in the \Windows directory and also in System32 but still get an error. Where does it need to be located?

**Comment by apmasell** [comment]
It tries to write a log file directly on `C:\`. You can customise the location of this file on:
https://github.com/miso-lims/rawprintserver/blob/master/RawPrintServer.cpp#L37

**Comment by scottw-finao** [comment]
we eventually figured it out - the error may have still been related to trying to open the log, but what it was trying to log was that when we rebooted the damn zebra browserprint utility auto-restarted and was holding the port open.

**Comment by scottw-finao** [comment]
(I actually hadn't seen the thread had been updated yet - I came back to add that we figured it out. But thanks for responding so fast :)
